name: repo-sync
on:
  schedule:
  - cron:  '*/59 * * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout kernel 6.6
      uses: actions/checkout@v4
      with:
          repository: joseflrs/a4
          ref: refs/heads/linux-6.6
    - name: repo-sync
      run: |
        git config --global http.postBuffer 524288000
        git remote add stable-rc https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git
        git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        git fetch stable-rc linux-6.6.y
        git reset --hard stable-rc/linux-6.6.y
        git push -f
      env:
        github_token: ${{ secrets.PAT }}
  repo-sync1:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout kernel 6.12
      uses: actions/checkout@v4
      with:
          repository: joseflrs/a4
          ref: refs/heads/linux-6.12
    - name: repo-sync1
      run: |
        git config --global http.postBuffer 524288000
        git remote add stable-rc https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git
        git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        git fetch stable-rc linux-6.12.y
        git reset --hard stable-rc/linux-6.12.y
        git push -f
      env:
        github_token: ${{ secrets.PAT }}
  repo-sync2:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout kernel 6.15
      uses: actions/checkout@v4
      with:
          repository: joseflrs/a4
          ref: refs/heads/linux-6.15
    - name: repo-sync2
      run: |
        git config --global http.postBuffer 524288000
        git remote add stable-rc https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git
        git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        git fetch stable-rc linux-6.15.y
        git reset --hard stable-rc/linux-6.15.y
        git push -f
      env:
        github_token: ${{ secrets.PAT }}
  repo-sync3:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout kernel 7.0
      uses: actions/checkout@v4
      with:
          repository: joseflrs/a4
          ref: refs/heads/linux-7.0
    - name: repo-sync3
      run: |
        git config --global http.postBuffer 524288000
        git remote add next https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
        git fetch next master
        git reset --hard next/master
        git push -f
      env:
        github_token: ${{ secrets.PAT }}

  repo-sync4:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout kernel master
      uses: actions/checkout@v4
      with:
          repository: torvalds/linux
          ref: refs/heads/master
    - name: repo-sync4
      run: |
        git config --global http.postBuffer 524288000
        git checkout origin/master
        git reset --hard
        git push -f
      env:
        github_token: ${{ secrets.PAT }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
